### ISSUE TITLE
User story: Any signed-up user can list a new space: signing up

### ISSUE THREAD

**Issue by peteburch223** [MuriloDalRi/makers_bnb#3]
As a person
So that I can use MBnB
I want to sign up to the service

**Comment by peteburch223** [comment]
Associated mock: homepage
Route: '/'

**Comment by shaneoston72** [comment]
Unresolved question:  

having a path(s) in app.rb and a separate controllers/<file> causes rspec to fail: 
`Failure/Error: erb :index
     
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /Users/shane/Drive/Projects/makers/week06/makers_bnb/app/controllers/views/index.erb`

Removing the paths from app.rb and putting them in server.rb fixes this issue.  

Why?

**Comment by shaneoston72** [comment]
BCrypt seems to accepting no password and creates a hash in DB.  This can occur if the user agent does not support 'required' in the html. we added a  helper method to the controller and coupled it with 'user.save'.  This works but only returns one error message (not related to the password) if user.save fails.  

How to add a custom error message to user.errors so it displays?

**Comment by shaneoston72** [comment]
:shipit:
